/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class al_franzis_jfanotify_FanotifyCom */

#ifndef _Included_al_franzis_jfanotify_FanotifyCom
#define _Included_al_franzis_jfanotify_FanotifyCom
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     al_franzis_jfanotify_FanotifyCom
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_al_franzis_jfanotify_FanotifyCom_init
  (JNIEnv *, jobject);

/*
 * Class:     al_franzis_jfanotify_FanotifyCom
 * Method:    add
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_al_franzis_jfanotify_FanotifyCom_add
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     al_franzis_jfanotify_FanotifyCom
 * Method:    read
 * Signature: (I)Lal/franzis/jfanotify/FanotifyEvent;
 */
JNIEXPORT jobject JNICALL Java_al_franzis_jfanotify_FanotifyCom_read
  (JNIEnv *, jobject, jint);

/*
 * Class:     al_franzis_jfanotify_FanotifyCom
 * Method:    write
 * Signature: (ILal/franzis/jfanotify/FanotifyResponse;)V
 */
JNIEXPORT void JNICALL Java_al_franzis_jfanotify_FanotifyCom_write
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
